# Generated by Django 4.1.2 on 2022-12-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
    ]
